version: '3'
services:
  server:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
    ports:
      - '5433:5432'
